In [9]:
x=[1,2,3,4,5]
y=[7,14,15,18,19]

In [10]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
import numpy as np
x=np.array(x)
y=np.array(y)
x=x.reshape(-1,1)
model.fit(x,y)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](1,)",[2.8]
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,6.2
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,1
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(1)
"singular_ singular_: array of shape (min(X, y),)Singular values of `X`. Only available when `X` is dense.","ndarray[float64](1,)",[3.16]


In [11]:
import pandas as pd
data = pd.read_csv('bp.csv')
data.head()

,Subject_ID,Age (years),Weight (kg),Systolic BP (mm Hg)
0,1,60,58,117
1,2,61,90,120
2,3,74,96,145
3,4,57,72,129
4,5,63,62,132


In [12]:
y = data['Systolic BP (mm Hg)']
x = data.drop(['Systolic BP (mm Hg)','Subject_ID'], axis=1)

In [13]:
y = data['Systolic BP (mm Hg)']
x = data.drop(['Systolic BP (mm Hg)','Subject_ID'], axis=1)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    random_state  = 42
)

print ("Training set:",
x_train.shape)
print("Testing Set:", x_test.shape)


Training set: (12, 2)
Testing Set: (4, 2)


In [15]:
from sklearn.linear_model import LinearRegression 
model=LinearRegression() 
model.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](2,)","[0.77,0.43]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](2,)","['Age (years)','Weight (kg)']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,44.35
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,2
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(2)


In [16]:
age = int(input("Enter the age of patient:"))
weight = int(input("Enter the weight of patient:"))
bp_ = model.predict([[age,weight]])
print("The Predicted Systolic BP is:", bp_[0])


The Predicted Systolic BP is: 157.91044285871703


c:\Users\hp\OneDrive\Desktop\AI Internship\srmccem\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [17]:
from sklearn.metrics import mean_squared_error
error=mean_squared_error(y_test, model.predict(x_test))
print("Mean Square Error:",error)

Mean Square Error: 91.8582299717074


HOUSE RENT PREDICTOR



In [18]:
import pandas as pd
data=pd.read_csv("House_Rent_Dataset.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner


In [19]:
 y =data['Rent']
 x=data.drop(['Rent','Posted On','Floor','Area Locality'],axis=1)

In [20]:
import category_encoders as ce
encoder=ce.LeaveOneOutEncoder()
X= encoder.fit_transform(x,y)

In [21]:
print(X)

      BHK  Size     Area Type          City  Furnishing Status  \
0       2  1100  18676.943967  11648.319312       22468.505513   
1       2   800  18672.853988  11629.198853       38727.130222   
2       2  1000  18674.080982  11634.934990       38728.463556   
3       2   800  18676.943967  11648.319312       22468.505513   
4       2   850  52405.438398  11653.099426       22469.883682   
...   ...   ...           ...           ...                ...   
4741    2  1000  52402.173269  20561.455594       38729.352444   
4742    3  2000  18669.173006  20545.307958       38723.130222   
4743    3  1750  52393.466260  20538.387543       38720.463556   
4744    3  1500  52389.112756  20526.853518       38716.019111   
4745    2  1000  52402.173269  20561.455594       22465.749173   

      Tenant Preferred  Bathroom  Point of Contact  
0         31216.953238         2      16706.291757  
1         31214.048795         1      16703.181337  
2         31214.920128         1      16704.1144

In [22]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x=scaler.fit_transform(X)

In [23]:
print(x)

[[0.2        0.13642053 0.27316184 ... 0.01795978 0.11111111 0.00321938]
 [0.2        0.09887359 0.27307371 ... 0.01780886 0.         0.00316481]
 [0.2        0.12390488 0.27310014 ... 0.01785413 0.         0.00318118]
 ...
 [0.4        0.21777222 0.99968293 ... 0.01758247 0.22222222 0.99965557]
 [0.4        0.1864831  0.99958912 ... 0.99558704 0.11111111 0.99954076]
 [0.2        0.12390488 0.99987054 ... 0.58744851 0.11111111 0.00319209]]


In [24]:
import pandas as pd 
x=pd.DataFrame(x,columns=X.columns)

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=42)
model=LinearRegression()
model.fit(x_train,y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies the convergence criterion of the underlying solver. `tol` isset as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. `tol` is set as `cond` of:func:`scipy.linalg.lstsq` when fitting on dense training data... versionadded:: 1.7.. versionchanged:: 1.9 Now supported on dense data, interpreted as the `cond` parameter.",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary <n_jobs>` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False
Name,Type,Value
"coef_ coef_: array of shape (n_features, ) or (n_targets, n_features)Estimated coefficients for the linear regression problem.If multiple targets are passed during the fit (y 2D), thisis a 2D array of shape (n_targets, n_features), while if onlyone target is passed, this is a 1D array of length n_features.","ndarray[float64](8,)","[ 28739.62,280544.56, 8065.85,...,-10798.66, 78466.48, 12316.87]"
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](8,)","['BHK','Size','Area Type',...,'Tenant Preferred','Bathroom', 'Point of Contact']"
"intercept_ intercept_: float or array of shape (n_targets,)Independent term in the linear model. Set to 0.0 if`fit_intercept = False`.",float64,-4.13e+04
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 0.24,int,8
rank_ rank_: intRank of matrix `X`. Only available when `X` is dense.,int64,np.int64(8)


In [26]:
new_house = pd.DataFrame({

'BHK': [2],

'Size': [1200],

'Area Type': ['Super Area'],

'City': ['Delhi'],

'Furnishing Status': ['Semi-Furnished'],

'Tenant Preferred': ['Family'],

'Bathroom': [2],

'Point of Contact': ['Contact Owner']

})

new_encoded = encoder.transform(new_house) 
new_scaled = scaler.transform(new_encoded) 
prediction = model.predict(new_scaled) 
print("Predicted Rent:", prediction[0])

Predicted Rent: 23745.90865439023


c:\Users\hp\OneDrive\Desktop\AI Internship\srmccem\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [27]:
import joblib

# Assuming you have already trained these three objects in your code:
# 1. your_encoder  (e.g., OneHotEncoder or LabelEncoder)
# 2. your_scaler   (e.g., StandardScaler or MinMaxScaler)
# 3. your_model    (e.g., LinearRegression, RandomForestRegressor, etc.)

# Create a dictionary matching what hpp.py expects to load
saved_data = {
    "encoder": encoder,
    "scaler": scaler,
    "model": model
}

# Save the dictionary to a .pkl file
joblib.dump(saved_data, "house_rent_prediction.pkl")

print("Model saved successfully!")

Model saved successfully!


In [28]:
import joblib
import pandas as pd
hpp=joblib.load("house_rent_prediction.pkl")
encoder=hpp["encoder"]
scaler=hpp["scaler"]
model=hpp["model"]
new_house = pd.DataFrame({
'BHK': [2],
'Size': [1200],
'Area Type': ['Super Area'],
'City': ['Delhi'],
'Furnishing Status': ['Semi-Furnished'],
'Tenant Preferred': ['Family'],
'Bathroom': [2],
'Point of Contact': ['Contact Owner']
})

new_encoded = encoder.transform(new_house) 
new_scaled = scaler.transform(new_encoded) 
prediction = model.predict(new_scaled) 
print("Predicted Rent:", prediction[0])

Predicted Rent: 23745.90865439023


c:\Users\hp\OneDrive\Desktop\AI Internship\srmccem\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [29]:
from sklearn.pipeline import Pipeline 
pipeline = Pipeline([
    ("encoder", ce.LeaveOneOutEncoder()),
    ("scaler", MinMaxScaler()), 
    ("model", LinearRegression()) ]) 
pipeline.fit(x_train, y_train) 

c:\Users\hp\OneDrive\Desktop\AI Internship\srmccem\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:420: UserWarning: Unknown section Example
  self[section] = content


,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('encoder', ...), ('scaler', ...), ...]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Only defined if theunderlying estimator exposes such an attribute when fit... versionadded:: 1.0",list,"['BHK', 'Size', 'Ar...pe', 'City', ...]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,8
,cols,[]
,verbose,0
,drop_invariant,False
,return_df,True


In [30]:
from sklearn.metrics import r2_score, mean_absolute_error 
y_pred = pipeline.predict(x_test) 
print("R² Score :", r2_score(y_test, y_pred)) 
print("MAE :", mean_absolute_error(y_test, y_pred)) 

R² Score : 0.5264285964561572
MAE : 22522.510766435247


In [31]:
joblib.dump( pipeline, "house_rent_pipeline.pkl" ) 
pipeline = joblib.load( "house_rent_pipeline.pkl" )
new_house = pd.DataFrame({
    "BHK":[2], "Size":[1200], 
    "Area Type":["Super Area"], 
    "City":["Delhi"], 
    "Furnishing Status":["Semi-Furnished"],
    "Tenant Preferred":["Family"],
    "Bathroom":[2],
    "Point of Contact":["Contact Owner"] }) 
 prediction = pipeline.predict(new_house) 
print(prediction)  

ValueError: could not convert string to float: 'Super Area'